FROM alpine:3.21

# Install required packages, csvkit, nodejs, npm and serve
RUN apk add --no-cache python3 py3-pip bash wget curl tzdata openssh-client openssl nodejs npm \
    && pip install --break-system-packages csvkit requests paramiko pandas lxml \
    && mkdir -p /data \
    && npm install -g serve

COPY getcsv.py /usr/local/bin/

RUN mkdir -p /secrets
COPY cromwell-sftp-private-id_rsa /secrets/
RUN chmod 600 /secrets/cromwell-sftp-private-id_rsa

ENV TZ=Europe/Budapest
RUN cp /usr/share/zoneinfo/Europe/Budapest /etc/localtime \
    && echo "Europe/Budapest" > /etc/timezone

# Set up cron to run script every day
RUN echo "0 3,9,15,21 * * * python3 /usr/local/bin/getcsv.py" > /etc/crontabs/root

EXPOSE 3000

CMD crond -l 2 && serve -s /csv-provider-data
