[SERVICE]
    Log_Level info
    Flush 1
    Daemon Off
    Parsers_File /fluentbit/parsers.conf

[INPUT]
    Name tail
    Path /var/log/stocksprite/app.log
    Tag stocksprite
    Read_from_Head true
    DB /fluentbit-data/fluent-bit.db
    Parser json-parser

[OUTPUT]
    Name opensearch
    Host opensearch
    Port 9200
    Match stocksprite
    Index stocksprite_index
    HTTP_User admin
    HTTP_Passwd admin
    Trace_Error On
    Retry_Limit false
    # Important for OpenSearch compatibility
    Suppress_Type_Name On