export const BindingKeys = {
    Logger: Symbol.for("Logger"),
    ICsvStreamFactory: Symbol.for("ICsvStreamFactory"),
    Redis: Symbol.for("Redis"),
    Ajv: Symbol.for("Ajv"),
    IUnasUpdater: Symbol.for("IUnasUpdater"),
    IAxiosHttpClient: Symbol.for("IAxiosHttpClient"),
    IUnasClient: Symbol.for("IUnasClient"),
    IQueuePublisher: Symbol.for("IQueuePublisher"),
    ISftpClient: Symbol.for("ISftpClient"),
    SettingsRepository: Symbol.for("SettingsRepository"),
    ProcessedItemsRepository: Symbol.for("ProcessedItemsRepository"),
    ValidatedUrlsRepository: Symbol.for("ValidatedUrlsRepository"),
    UnasCacheRepository: Symbol.for("UnasCacheRepository"),
    WarehouseRepository: Symbol.for("WarehouseRepository"),
    FileDataConnector: Symbol.for("FileDataConnector"),
    HttpDataConnector: Symbol.for("HttpDataConnector"),
    SftpDataConnector: Symbol.for("SftpDataConnector"),
    DataSourceMapper: Symbol.for("DataSourceMapper"),
    UnasDataSourceMapper: Symbol.for("UnasDataSourceMapper"),
};
