services:      
  redis-stack:
    image: redis/redis-stack:7.4.0-v6
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
      
  app:
    build:
      context: ./containers/app
    restart: always
    depends_on:
      - redis-stack
    environment:
      - REDIS_HOST=redis-stack
      - REDIS_PORT=6379
      - TZ=Europe/Budapest
      - NODE_ENV=prod
    volumes:
      - ./containers/app/logs:/app/logs
        ./app/secrets:/run/secrets:ro
      - ./containers/app/app/secrets:/run/secrets:ro
      - csv-provider-data:/csv-provider-data:ro

  opensearch:
    image: opensearchproject/opensearch:3.1.0
    restart: always
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Connecticut4847!
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200" # OpenSearch REST API
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.1.0
    restart: always
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      - opensearch

  fluentbit:
    image: fluent/fluent-bit:4.0.3
    restart: always
    depends_on:
      - opensearch
    volumes:
      - ./containers/fluentbit/fluentbit.conf:/fluentbit/fluentbit.conf:ro
      - ./containers/fluentbit/parsers.conf:/fluentbit/parsers.conf:ro
      - ./containers/app/logs:/var/log/stocksprite:ro
      - fluentbit-data:/fluentbit-data
    command: ["-c", "/fluentbit/fluentbit.conf"]

  csv-provider:
    build:
      context: ./containers/csv-provider
    restart: always
    ports:
      - "8085:3000"
    volumes:
      - csv-provider-data:/csv-provider-data

volumes:
  opensearch-data:
  fluentbit-data:
  redis-data:
  csv-provider-data:
