FROM node:22-bookworm-slim  AS base

# Install cron and tzdata
RUN apt-get update && apt-get install -y --no-install-recommends cron tzdata \
    && rm -rf /var/lib/apt/lists/* \
    && npx playwright install --with-deps chromium

# Set Timezone
ENV TZ=Europe/Budapest
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# -----------------Final stage------------------
FROM base AS final

WORKDIR /app
COPY index.js package.json /app
RUN npm i --only=production && npm install -g serve

RUN printf "0 19 * * * . /etc/profile; /usr/local/bin/node /app/index.js\n\n" > /var/spool/cron/crontabs/root \
    && chown root:crontab /var/spool/cron/crontabs/root \
    && chmod 600 /var/spool/cron/crontabs/root \
    && touch /var/log/cron.log

EXPOSE 3000

CMD cron && serve -s /csv-provider-data