export const BindingKeys = {
    IConfiguration: Symbol.for("IConfiguration"),
    Logger: Symbol.for("Logger"),
    ICsvStreamFactory: Symbol.for("ICsvStreamFactory"),
    Redis: Symbol.for("Redis"),
    Ajv: Symbol.for("Ajv"),
    IUnasTranslator: Symbol.for("IUnasTranslator"),
    IAxiosHttpClient: Symbol.for("IAxiosHttpClient"),
    IUnasClient: Symbol.for("IUnasClient"),
    IQueuePublisher: Symbol.for("IQueuePublisher"),
    ICsvStreamProcessor: Symbol.for("ICsvStreamProcessor"),
    SettingsRepository: Symbol.for("SettingsRepository"),
    ValidatedUrlsRepository: Symbol.for("ValidatedUrlsRepository"),
    UnasCacheRepository: Symbol.for("UnasCacheRepository"),
    WarehouseRepository: Symbol.for("WarehouseRepository"),
    FileDataConnector: Symbol.for("FileDataConnector"),
    HttpDataConnector: Symbol.for("HttpDataConnector"),
    DataSourceMapper: Symbol.for("DataSourceMapper"),
    UnasDataSourceMapper: Symbol.for("UnasDataSourceMapper"),
    ParsedQueue: Symbol.for("ParsedQueue"),
    TranslatedQueue: Symbol.for("TranslatedQueue"),
    DataSourceRuleCollection: Symbol.for("DataSourceRuleCollection"),
    DataSourceRuleProvider: Symbol.for("DataSourceRuleProvider"),
};
